repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.10
    hooks:
    -   id: shellcheck
