version: '2'
volumes:
    ubiquity-config:
services:
  ubiquity-controller:
    image: lsioarmhf/unifi
    ports:
      - "3478/udp"
      - "10001/udp"
      - "8080"
      - "8081"
      - "8443"
      - "8843"
      - "8880"
      - "6789"
    volumes:
      - "ubiquity-config:/config"
