version: '2'
volumes:
  unifi-config:
services:
  backup:
    build: ./backup
    restart: unless-stopped
    volumes:
      - "unifi-config:/config"
  unifi-controller:
    depends_on:
      - backup
    image: linuxserver/unifi-controller:arm64v8-5.11.46-ls36
    environment:
      - PUID=1000
      - PGID=1000
    # Ports are documented in https://help.ubnt.com/hc/en-us/articles/218506997
    ports:
      - "3478:3478/udp"
      - "6789:6789"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "27117:27117" # Port used for local-bound database communication.
      - "5656-5699:5656-5699/udp" # Ports used by AP-EDU broadcasting.
      - "10001:10001/udp"
      - "1900:1900/udp" # Port used for "Make controller discoverable on L2 network" in controller settings.
    restart: unless-stopped
    volumes:
      - "unifi-config:/config"
