version: '2'
volumes:
  unifi-config:
services:
  backup:
    build: ./backup
    restart: unless-stopped
    volumes:
      - "unifi-config:/config"
  unifi-controller:
    depends_on:
      - backup
    image: linuxserver/unifi-controller:arm64v8-5.11.46-ls36
    # Ports are documented in https://help.ubnt.com/hc/en-us/articles/218506997
    ports:
      - "3478:3478/udp" # Port used for STUN.
      - "8080:8080" # Port used for device and controller communication.
      - "8443:8443" # Port used for controller GUI/API as seen in a web browser.
      - "8880:8880" # Port used for HTTP portal redirection.
      - "8843:8843" # Port used for HTTPS portal redirection.
      - "6789:6789" # Port used for UniFi mobile speed test.
      - "27117:27117" # Port used for local-bound database communication.
      # See https://forums.balena.io/t/large-number-of-forwarded-udp-ports-break-the-device/36364
      # - "5656-5699:5656-5699/udp" # Ports used by AP-EDU broadcasting.
      - "10001:10001/udp" # Port used for device discovery
      - "1900:1900/udp" # Port used for "Make controller discoverable on L2 network" in controller settings.
    restart: unless-stopped
    volumes:
      - "unifi-config:/config"
