version: '2'
volumes:
  ubiquity-config:
services:
  backup:
    build: ./backup
    restart: unless-stopped
    volumes:
      - "ubiquity-config:/config"
  ubiquity-controller:
    depends_on:
      - backup
    image: linuxserver/unifi-controller:arm32v7-latest
    ports:
      - "3478:3478/udp"
      - "6789:6789"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "10001:10001/udp"
    restart: unless-stopped
    volumes:
      - "ubiquity-config:/config"
