FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster

# Install rclone
RUN apt-get update \
  && apt-get install --assume-yes --no-install-recommends rclone \
  && rm -rf /var/lib/apt/lists/*

# Configure rclone
COPY rclone.conf /var/rclone/

# Install scripts
COPY unifi-backup.bash /usr/bin/

CMD mkdir -p /var/gcp && \
  echo $SERVICE_ACCOUNT_FILE > /var/gcp/service_account_file.json && \
  unifi-backup.bash
