FROM resin/%%RESIN_MACHINE_NAME%%-ubuntu:latest

# Install rclone
RUN apt-get update && \
    apt-get -y install curl zip man-db && \
    curl https://rclone.org/install.sh | bash

# Configure rclone
COPY rclone.conf /var/rclone/

# Install scripts
COPY unifi-backup /usr/bin/

CMD mkdir -p /var/gcp && \
  echo $SERVICE_ACCOUNT_FILE > /var/gcp/service_account_file.json && \
  unifi-backup
